fail_fast: false
repos:
  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: bash
        language: system
        files: \.(cpp|h|hpp)$
        exclude: ^build
        args: [-c, 'clang-tidy --config-file=.clang-tidy --warnings-as-errors="cppcoreguidelines-*,modernize-use-nullptr" "$@" -- -x c++ -std=c++17', --]
