fail_fast: false
repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        files: \.(c|cc|cxx|cpp|h|hh|hpp|hxx)$
        args: [-i]
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy
        language: system
        files: \.(c|cc|cxx|cpp)$
