add_subdirectory("allocator")
add_subdirectory("command")
add_subdirectory("data")
add_subdirectory("device")
add_subdirectory("main")
add_subdirectory("pipeline")
add_subdirectory("presentation")
add_subdirectory("renderer")
add_subdirectory("shader")
add_subdirectory("sync")
add_subdirectory("utils")
add_subdirectory("validation")
add_subdirectory("window")

add_library(Avalon_src INTERFACE)

target_link_libraries(Avalon_src INTERFACE Avalon_window Avalon_shader)
