name: Build Windows
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Vulkan SDK
        shell: pwsh
        run: |
          curl -LO "https://sdk.lunarg.com/sdk/download/1.3.296.0/windows/VulkanSDK-1.3.296.0-Installer.exe"
          
          Start-Process -FilePath .\VulkanSDK-1.3.296.0-Installer.exe -ArgumentList "/S" -Wait
          Remove-Item VulkanSDK-Installer.exe

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Checkout Code
        uses: actions/checkout@v3
