name: Build Windows
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Prepare Vulkan SDK
        uses: NcStudios/VulkanCI@v1.0
        with:
          # VulkanSDK version to use
          # Must be a supported version
          # The default value is 1.3.283.0
          sdkVersion: 1.3.283.0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Checkout Code
        uses: actions/checkout@v3
