name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Basic Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ build-essential python3 python3-pip
          sudo python3 -m pip install conan pre-commit --ignore-installed urllib3

      - name: Install Conan Dependencies
        run: |
          sudo -E conan profile detect
          sudo -E conan install . -c tools.system.package_manager:mode=install --build=missing -s build_type=Debug

      - name: Install Vulkan Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libvulkan-dev libxcb1-dev

      - name: Build Project
        run: |
          sudo cmake \
              -S .  \
              -B build  \
              -G "Unix Makefiles" \
              -D CMAKE_TOOLCHAIN_FILE=Debug/generators/conan_toolchain.cmake \
              -D CMAKE_POLICY_DEFAULT_CMP0091=NEW \
              -D CMAKE_BUILD_TYPE=Debug
          sudo cmake --build build

      - name: Lint
        run: sudo pre-commit run --all-files

      - name: Run Tests
        run: |
          sudo cd build 
          sudo ctest
