name: Build

on:
  push:
  pull_request:
    # Triggers on any pull request for all branches
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Basic Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ build-essential python3 # Install CMake and GCC
          pip install conan

      - name: Build Project
        run: |
          conan profile detect
          conan install . --build=missing -s build_type=Debug
          cmake \
              -S .  \
              -B build  \
              -D CMAKE_TOOLCHAIN_FILE='build/generators/conan_toolchain.cmake'
          cmake --build build
