name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Basic Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ build-essential python3
          pip install conan pre-commit

      - name: Install Conan Dependencies
        run: |
          conan profile detect
          sudo conan install . -c tools.system.package_manager:mode=install --build=missing -s build_type=Debug


      - name: Install Vulkan libraries
        run: |
          sudo apt update
          sudo apt install libvulkan-dev libxcb1-dev

      - name: Build Project
        run: |
          cmake \
              -S .  \
              -B build  \
              -G "Unix Makefiles" \
              -D CMAKE_TOOLCHAIN_FILE=Debug/generators/conan_toolchain.cmake \
              -D CMAKE_POLICY_DEFAULT_CMP0091=NEW \
              -D CMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Lint
        run: |
          pre-commit run --all-files

      - name: Run Tests
        run: |
          cd build 
          ctest
