name: Pre-commit Checks

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Basic Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy uncrustify cppcheck

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pre-commit
        run: |
          pip install pre-commit
      - name: Install Pre-commit Hooks
        run: |
          pre-commit install-hooks

      - name: Run Pre-commit
        run: |
          pre-commit run --all-files

      - name: Run Clang-Tidy
        run: |
          clang-tidy **/*.cpp -- -std=c++17

      - name: Run Uncrustify
        run: |
          uncrustify -c uncrustify.cfg --replace **/*.cpp

      - name: Run Cppcheck
        run: |
          cppcheck --enable=all --std=c++17 --suppress=missingIncludeSystem **/*.cpp
